meicansoft:
  target: prd
  outputs:
    prd:
      type: bigquery
      method: service-account
      keyfile: /Users/mfelipemota/Projects/dbt_dengue/meicansoft-prd-a0c7a86be733.json
      project: meicansoft-prd
      schema: projeto_dengue_izabela
      location: us-central1
      threads: 16
      job_execution_timeout_seconds: 300
      priority: interactive